### ISSUE TITLE
Issues on CPFlow deployment on linux

### ISSUE THREAD

**Issue by eeethon** [idnm/cpflow#1]
Hello, I have encountered some issues when deploying CPFlow on Linux recently. Firstly, I am using Python 3.8, and when I directly ran `pip install cpflow`, the installed version of Qiskit was 1.2.4 and the version of jaxlib was higher than 0.3.5. However, the latest CPFlow-0.0.4 requires jaxlib to be in the range of 0.3.0 to 0.3.5, but this version range is no longer available on PyPI. Although I managed to install it through other methods, new issues arose. A higher version of Qiskit is causing CPFlow to not run properly. I was able to get it working with older versions (qiskit==0.46.0, qiskit-ibm-runtime==0.18.0). The version of qiskit-terra that comes with this qiskit is higher than 0.20.0, which is the version you specified for installation. Without installing the version you recommended, the program runs successfully and outputs:

```
7 successful. cz counts are:
[8, 8, 8, 8, 8, 9, 10]
< ccz_chain | Rational | loss: 0.0 | CZ count: 8 | CZ depth: 8 >
```

This result is inconsistent with what you have stated in the README, and there are no circuit prints, but the `ccz_chain` file is generated in the `result` directory. I also tried it on Colab but encountered similar issues. Could you please advise on the correct environment setup to properly run the files from your tutorial?

**Comment by eeethon** [comment]
I can show the circuit with an extra plt.show() after d.circuit.draw(). However, I can't use the Clifford+T.

**Comment by idnm** [comment]
Hi @eeethon! Thanks for your interest in CPFlow and sorry it led you to the [dependency hell](https://en.wikipedia.org/wiki/Dependency_hell).

Unfortunately, CPFlow is not currently supported or kept updated. If your goal is to find the absolute shortest possible circuit for a small unitary, it still may be worth it to try and setup everything so that it works.

However, if you are looking for a generic quantum circuit compiler you'd probably be better off using some of the more versatile and actively supported ones, such as [BQSKit](https://github.com/BQSKit/bqskit).

Hope that helps!

**Comment by eeethon** [comment]
Thank you very much for your reply, @idnm. CFPlow is still very valuable for small-scale circuit optimization.  Several days ago, I noticed that you had provided the specific environment configuration at the bottom of the tutorial's Jupyter Notebook. I apologize for not seeing it earlier. With this information, I can replicate the environment. Additionally, two days ago, I learned about other circuit optimization tools from the papers, including BQSKit, and I plan to try these tools next. Thank you again for your reply!
